---
url: http://rubini.us
safe: true
lsi: false
permalink: pretty
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
  - drafts
markdown: rdiscount
highlighter: pygments
port: 9876
